# Labels Configuration
# Run: gh label import .github/labels.yml

- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: question
  color: d876e3
  description: Further information is requested

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: stale
  color: fef2c0
  description: Inactive issue or PR

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file

- name: security
  color: d93f0b
  description: Security related issue

- name: breaking
  color: b60205
  description: Breaking change

- name: keyboard
  color: 1d76db
  description: Related to keyboard backlight

- name: battery
  color: 0e8a16
  description: Related to battery/charging

- name: fan
  color: fbca04
  description: Related to fan control

- name: power
  color: 5319e7
  description: Related to power profiles
