<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\src\LegionLoqControl.Application\LegionLoqControl.Application.csproj" />
    <ProjectReference Include="..\src\LegionLoqControl.Contracts\LegionLoqControl.Contracts.csproj" />
    <ProjectReference Include="..\src\LegionLoqControl.Domain\LegionLoqControl.Domain.csproj" />
    <ProjectReference Include="..\src\LegionLoqControl.Infrastructure.Windows\LegionLoqControl.Infrastructure.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
